### ISSUE TITLE
Sample app for Android Wear

### ISSUE THREAD

**Issue by kshoji** [kshoji/BLE-MIDI-for-Android#10]
I've tried testing with my ZenWatch, it can treat the BLE Central feature.
Add a synthesizer, or MIDI recorder function with a simple user interface.

**Comment by Omegatdc112** [comment]
Does this work with midi keyboards?

**Comment by kshoji** [comment]
Yes, the Wear app sample can work with BLE MIDI keyboards. 
But there is one problem, the Android Wear device doesn't have a speaker, so the external Bluetooth speaker will be needed when the app want to play sound.

My testing environment is ASUS ZenWatch(with Android Wear 5.1.1), Bluetooth speaker, and Miselu C.24 BLE MIDI keyboard.
The MIDI events logging is working well, but there is too long latency on playing sound with my environment. The cause of the latency seems in the speaker's sound buffer.

**Comment by Omegatdc112** [comment]
Can this app or your MIDI driver app work with an Alcatel Fierce 2? Smartphone?

Matthew Cunningham

From: Kaoru Shoji
Sent: ‎Sunday‎, ‎June‎ ‎7‎, ‎2015 ‎11‎:‎00‎ ‎PM
To: kshoji/BLE-MIDI-for-Android
Cc: Omegatdc112

Yes, the Wear app sample can work with BLE MIDI keyboards. 
But there is one problem, the Android Wear device doesn't have a speaker, so the external Bluetooth speaker will be needed when the app want to play sound.

My testing environment is ASUS ZenWatch(with Android Wear 5.1.1), Bluetooth speaker, and Miselu C.24 BLE MIDI keyboard.
The MIDI events logging is working well, but there is too long latency on playing sound with my environment. The cause of the latency seems in the speaker's sound buffer.

**Comment by kshoji** [comment]
Sorry for late reply.

I've googled about Alcatel Fierce 2.
I found its OS is a Android 4.4.2, and it has Bluetooth 4.0 features.
So the library's sample app may be work with BLE Central mode.

The BLE MIDI Peripheral devices(BLE MIDI keyboard, or controller etc.) are also needed to test the sample app.

Regards,
Kaoru
